version: 2

models:
  - name: stg_google_sheet
    description: Information about the companies contained in the study, taken from the google sheet provided by hiflylabs.
    columns:
      - name: _pk
        description: Primary key.
        tests:
          - unique
          - not_null
      - name: tags
        description: Keywords connected with the corresponding organization.
      - name: tags_array
        description: An array of the keywords.
      - name: l1_type
        description: Values in the range [modern_data_stack, null].
      - name: l2_type
        description: Values in the range [ingestion, orchestration, devops, transformation, data_platform, reverse_etl, business_intellegence].
      - name: l3_type
        description: Value in the range [dbt package, null].
      - name: organization
        description: Organization name.
      - name: repository_name
        description: Repository name.
      - name: repository_account
        description: Repository account.
      - name: creationtime_at_datetime_utc
        description: Time of emission in UTL format.
      - name: is_open_source_available
        description: Boolean values - true or false.